NAMESPACE: 'default'
K8S_REPLICAS: '1'
K8S_MAX_UNAVAIL: '1'
K8S_MAX_SURGE: '1'
K8S_REQ_MEM: '64Mi'
K8S_REQ_CPU: '100m'
K8S_LIMIT_MEM: '128Mi'
K8S_LIMIT_CPU: '150m'
AUTOSCALE_MIN_REPLICA: '1'
AUTOSCALE_MAX_REPLICA: '2'
AUTOSCALE_CPU_PERCENTAGE: '50'
DOCKER_APP_IMAGE: shubhamdevops2/display:1.0.1-2022-10-30-15-34-37-main
APP_LOCATION: 'app/*'
CONTAINER_PORT: 8080